# Generated by Django 3.0.7 on 2020-12-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerleague', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[{'Goalie', 'G'}, {'Defender', 'D'}, {'M', 'Midfielder'}, {'F', 'Forward'}], max_length=10),
        ),
    ]
