# Generated by Django 3.0.7 on 2020-12-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerleague', '0002_auto_20201202_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
