# Generated by Django 3.0.7 on 2020-12-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerleague', '0003_auto_20201202_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score_awayteam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='score_hometeam',
            field=models.IntegerField(default=0),
        ),
    ]
